export const ROUTES = {
  // Admin
  dashboard: "dashboard",
  category: "/category",
  comment: "/comment",
  commentView: "/commentView",
  order: "/order",
  orderDetail: "/orderDetail",
  orderView: "/orderView",
  productList: "/productList",
  productView: "/productView",
  productUpdate: "/productUpdate",
  productCreate: "/productCreate",
  profile: "/profile",
  discount: "/discount",
  discountCreate: "/discountCreate",
  // Public
  home: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  shop: "/shop",
  cart: "/cart",
  checkout: "/checkout",
  services: "/services",
  contact: "/contact",
  about: "/about",
  // Customer account
  myOrders: "/my-orders",
  myProfile: "/my-profile",
};
